### ISSUE TITLE
doppelter Aufruf für prediction nötig

### ISSUE THREAD

**Issue by MarHai** [pollyvote/pollyvoter#10]
Warum klappt `pv$predictions$pollyvote(pv)`, aber `pv$predictions$pollyvote()` nicht? Also mir ist klar, warum das so ist, aber wäre es nicht wesentlich user-freundlicher, wenn zweiteres auch klappt? Wenn also der Default-Wert für pv an der Stelle einfach das Objekt ist, innerhalb dessen die Prediction-Funktion aufgerufen wird?

**Comment by maierhofert** [comment]
Es ist im Paket nicht vorgesehen die Funktionen direkt über pv$predictions$pollyvote() aufzurufen, sondern nur indirekt über predict(pv, method = "pollyvote").
Daher würde ich es bei dem aktuellen Design lassen, bei dem pv als erstes Argument übergeben werden muss.
