### ISSUE TITLE
Dokumentation von Plot-Funktionen nicht gut auffindbar

### ISSUE THREAD

**Issue by MarHai** [pollyvote/pollyvoter#11]
Die Plot-Funktionen sind nicht wirklich auffindbar. Man muss schon genau selbst wissen, dass (und warum) man "prediction_election" (wie in der Vignette) oder gar ".error_calc_method" in die Plot-Funktion schreiben muss. Bitte nachziehen und irgendwo dokumentieren. Ließe sich das vielleicht zentral in `?pollyvoter` unterbringen?

**Comment by maierhofert** [comment]
Die plot Funktion ist in der Doku von create_pollyvote verlinkt.
Die Doku zu plot.pollyvoter wurde erweitert.
