### ISSUE TITLE
Importfunktionen

### ISSUE THREAD

**Issue by andinatro** [pollyvote/pollyvoter#2]
Ihr schreibt:

> Daten liegen meist als Excel- oder CSV-Dateien vor, was nicht weiter relevant für das vorliegende R-Paket sein soll. Importiert wird aus den üblichen R-Formaten, etwaige read.table-Befehle erfolgen außerhalb des Pakets. Da die Daten nicht in einer einzelnen Datei vorliegen, sind mehrere Import-Funktionen vonnöten, die auch das spätere Hinzufügen neuer einzelner Daten abdecken sollen.

D.h. die Daten sollen schon im richtigen Format vorher in R eingelesen sein? Was spricht dagegen, dafür eine Methode zur Verfügung zu stellen? 

Die mitgeschickte `xlsx` hat sehr viele Tabs - da sind ja auch schon Ergebnisse mit drin. Meine Frage hier ist: Wie sieht denn so eine Beispieldatei aus (von der Struktur her)? 

Und dann noch eine generelle Frage:

Dieser _Datencontainer_ soll dann praktisch eine Teilmenge von allen Daten sein, die jeweils nur das spezifizierte enthält? Also man startet mit einem riesigen Datensatz und trifft dann durch die "set"-Funktionen eine Auswahl? Das habe ich leider noch nicht ganz verstanden - wäre super, wenn ihr das nochmal verdeutlichen könntet.

**Comment by MarHai** [comment]
> D.h. die Daten sollen schon im richtigen Format vorher in R eingelesen sein? Was spricht dagegen, dafür eine Methode zur Verfügung zu stellen?

Spricht grundsätzlich nichts dagegen. Allerdings sind die Daten nicht immer einheitlich vorliegend, sodass ich davon ausgegangen bin, dass es klüger wäre, diese doch sehr unterschiedlichen Datenimport- und Datenaufbereitungsschritte außerhalb des Pakets zu machen (Stichwort: Single Responsibility).


Die zweite Frage verlangt eine etwas ausführlichere Antwort:
Grundsätzlich kommen die Daten meist aus unterschiedlichen Quellen, also mal was händisch eingetragenes, mal was aus einem schön aufbereiteten CSV, mal aus einer API. Und der Regelfall sieht so aus, dass man diese Datensammlung aus verschiedenen Quellen regelmäßig (zB täglich) macht. Die ganzen Daten müssen dann jeden Tag zusammengeführt werden, damit man daraus eben die Aggregation und Berechnung und Prognose machen/ableiten kann. Die Idee ist deshalb, einen zentralen _Datencontainer_ zu definieren, der alle Daten enthält und mit dem dann gerechnet werden kann.
Ich stelle mir das so vor, dass ich mir im Laufe eines Wahlkampfs ein R-Script bastle, das Daten aus unterschiedlichen Quellen sammelt und dieses R-Paket damit füllt. Damit entsteht ein (der) Datencontainer, mit dem im weiteren Verlauf des R-Scripts die Berechnungen und die Extraktion der Daten für bestimmte Visualisierungen angestoßen werden. Ändert sich also der Tag oder eine Komponente, dann passe ich den ersten Teil des Scripts an, der zweite Teil des Scripts bleibt aber bestehen, weil der immer auf den Datencontainer aufsetzt (dem Export und der Prognose ist also egal, wieviele Daten bereits eingeflossen sind).
Parallel habe ich so den Vorteil, dass ich sowohl den schön aufbereiteten Datencontainer als auch die R-Scripte der Öffentlichkeit zur Verfügung stellen kann, da das Format klar definiert ist.

Der _Datencontainer_ ist also quasi der Versuch, das Excel-File für die BTW13 (in der Vergangenheit gabs auch schon - alternativ zum Excel-File - ein Sammelsurium an CSVs (POTUS12) bzw. ein Sammelsurium an Google-Sheets-Files (POTUS16)) in ein Standardformat zu überführen, das sowohl die Modellspezifikationen als auch die Daten enthält.


Damit ergeben sich noch Antworten auf deine Teilfragen:

> Wie sieht denn so eine Beispieldatei aus (von der Struktur her)?

Die gibt es nur bedingt. Wir haben ein schönes Format für die POTUS16-Wahl erarbeitet (einsehbar unter pollyvote.com/api), aber das hält nicht für Mehrparteienwahlen und es enthält zahlreiche Meta-Infos, die hier nicht vonnöten sind. Um also direkt auf die Frage zu antworten: Gibts nicht.

> Dieser Datencontainer soll dann praktisch eine Teilmenge von allen Daten sein, die jeweils nur das spezifizierte enthält?

Der Datencontainer enthält _alles_ (Daten, Spezifikationen) und erlaubt, darin zu operieren.

> Also man startet mit einem riesigen Datensatz und trifft dann durch die "set"-Funktionen eine Auswahl?

Der Datencontainer ist der riesige Datensatz, die `set`-Funktionen ermöglichen das Ändern von Daten darin.

**Comment by andreasgraefe** [comment]
Mario hat das ausgezeichnet beschrieben, so dass ich im Moment nicht wüsste, was ich ergänzen sollte. Bei Rückfragen stehe ich aber selbstverständlich zur Verfügung.

**Comment by andinatro** [comment]
Vielen Dank für die ausführlichen Erläuterungen!

Das heißt dieser im ersten Teil deines R-Skripts zusammengebastelte Datencontainer muss eine klar definierte Struktur haben,  mit der das R-Paket dann weiter umgehen kann?

**Comment by MarHai** [comment]
Genau. Das genaue Format kannst du festlegen, die Daten werden
ausschließlich über die von dir zur Verfügung gestellten Funktionen
gefüttert.

Am 03.04.2017 4:27 nachm. schrieb "Andreas Hueck" <notifications@github.com

**Comment by andinatro** [comment]
Hallo zusammen,

nach längerer Pause (Urlaub) hier noch einige Punkte von meiner Seite, zu denen ich mir intensiv Gedanken gemacht habe:

Als Datencontainer würde ich einen R-üblichen data.frame im long format empfehlen - also mit möglichst wenigen Spalten. Pro Datenpunkt gibt es dann eine Zeile im Datensatz.

Das sähe dann (in etwa) so aus:

| Wahl | Wahldatum | Umfragedatum | Komponente | Partei | Anteil | ... |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| BTW2017  | 2017-09-24 | 2017-04-15 | Emnid | CDU/CSU | 35 | ... |
| BTW2017  | 2017-09-24 | 2017-04-15 | Emnid | SPD | 31 | ... |
| BTW2017  | 2017-09-24 | 2017-04-15 | Emnid | GRUENE | 7 | ... |
| ...  |  |  | |  | | |
| POTUS2016  | 2016-11-08 | 2016-10-10 | Blub | DEMOCRATS | 55 | ... |
| ...  |  |  | |  | | |

Für das tatsächliche Ergebnis könnte dann z.B. einfach eine weitere Spalte angefügt werden (z.B. `Ergebnis`), die entweder das Ergebnis oder `NA` enthält, falls die Wahl erst in der Zukunft ist; ebenso für Regionen, Mehrheits-/Verhältniswahl, etc.

Bei einem Datencontainer in einem solchen Format braucht es dann auch keine gesonderten Funktionen, um Komponenten hinzuzufügen - die entsprechenden Zeilen können einfach angehängt werden.

Ebenso stehen R-Funktionen zur Aggregation und Selektion sowie Projektion der Daten zur Verfügung (z.B. im R-Paket `dplyr`), die sehr einfach zu handhaben sind.

Am Ende bleibt dann nicht mehr viel übrig für das Paket - zwanghaft Funktionen als "Wrapper" um bestehende Funktionalität zu schreiben, halte ich für nicht besonders sinnvoll.

Was denkt ihr dazu?

**Comment by MarHai** [comment]
Halte ich grundsätzlich für eine gute Idee, aber kriegst du da auch die Spezifikationen unter? Also zB die Regionen oder die Wahltermine? Dachte alternativ an eine Liste, die wiederum aus Data-Frames besteht, bin aber ein großer Freund davon, auf die von `plyr` zur Verfügung gestellten Funktionen zurückzugreifen. Keine Ahnung, ob das mit Lists auch ginge.

**Comment by adibender** [comment]
Grundsätzlich kann man in data.frames auch Spalten anlegen, die Listen-Elemente haben. 
D.h. man kann das ganze auch in das [tidyverse](http://tidyverse.org/)-Framework einbinden. 
Ich arbeite zur Zeit an sowas für das `coalitions` package. Beispiel weiter unten (Details). 

(Btw: `plyr` und `dplyr` haben ganz andere Philosophie, dementsprechend gehört `plyr` z.B. nicht zum "tidyverse"). 

- Vorteil: 
  - Die ganze Funktionalität des `tidyverse` steht einem bequem zur Verfügung
  -  Wenn man `tibbles` (spezielle data frames) benutzt. Können diese auch z.B. in einer sqlite Datenbank gespeichert sein und die `dplyr` Funktionen würden trotzdem darauf funktionieren. 

- Nachteil: 
  - Es ist alles ziemlich cutting edge. z.B. kommt demnächst auch einen neue dplyr Version 0.6.0 raus, bei der sich ggü. 0.5.0 relativ viel ändert. Könnte also zusätzlichen Aufwand bedeuten Kompatibilität mit äteren/neueren Versionen zu gewährleisten. 
  - Steile Lernkurve: Viele neue Funktionen und eine andere Denkweise beim programmieren (functional programming).  Es hilft, sich neben `dplyr` noch gut mit mindestens `tidyr` und `purrr` auszukennen. 

<details>

```r
library(magrittr)
library(purrr)
library(dplyr)
library(tidyr)
devtools::install_github("adibender/coalitions")
library(coalitions)

## Emnid Umfragen von wahlrecht.de ziehen
emnid <- scrape_wahlrecht()
head(emnid)
##        DATUM      START        END CDU SPD GRUENE FDP LINKE AFD SONSTIGE BEFRAGTE
## 1 2017-04-15 2017-04-06 2017-04-12  35  31      7   6     9   9        3     2436
## 2 2017-04-08 2017-03-30 2017-04-05  35  33      7   5     8   9        3     1958
## 3 2017-04-01 2017-03-23 2017-03-29  33  33      7   6     8   8        5     2416
## 4 2017-03-25 2017-03-16 2017-03-22  33  33      8   5     8   9        4     2450
## 5 2017-03-18 2017-03-09 2017-03-15  33  32      8   5     8   9        5     1832
## 6 2017-03-11 2017-03-02 2017-03-08  33  33      7   6     8   8        5     1882



elong <- collapse_parties(emnid)
## erzeugt spalte survey, welche eine Liste ist
# pro Zeile enthält Liste ein data frame/tibble mit der Umfrage im Long-Format
# Vorteil: Keine reduntanten Einträge für Daum, Befragte, etc. 

head(elong)
## # A tibble: 6 × 5
##        DATUM      START        END BEFRAGTE           survey
##       <date>     <date>     <date>    <dbl>           <list>
## 1 2017-04-15 2017-04-06 2017-04-12     2436 <tibble [7 × 3]>
## 2 2017-04-08 2017-03-30 2017-04-05     1958 <tibble [7 × 3]>
## 3 2017-04-01 2017-03-23 2017-03-29     2416 <tibble [7 × 3]>
## 4 2017-03-25 2017-03-16 2017-03-22     2450 <tibble [7 × 3]>
## 5 2017-03-18 2017-03-09 2017-03-15     1832 <tibble [7 × 3]>
## 6 2017-03-11 2017-03-02 2017-03-08     1882 <tibble [7 × 3]>


## vom genesteten Format zurück ins long format (für die erste Zeile)
elong %>% slice(1) %>% unnest()
## # A tibble: 7 × 7
##        DATUM      START        END BEFRAGTE    PARTY PERCENT  VOTES
##       <date>     <date>     <date>    <dbl>    <chr>   <dbl>  <dbl>
## 1 2017-04-15 2017-04-06 2017-04-12     2436      CDU      35 852.60
## 2 2017-04-15 2017-04-06 2017-04-12     2436      SPD      31 755.16
## 3 2017-04-15 2017-04-06 2017-04-12     2436   GRUENE       7 170.52
## 4 2017-04-15 2017-04-06 2017-04-12     2436      FDP       6 146.16
## 5 2017-04-15 2017-04-06 2017-04-12     2436    LINKE       9 219.24
## 6 2017-04-15 2017-04-06 2017-04-12     2436      AFD       9 219.24
## 7 2017-04-15 2017-04-06 2017-04-12     2436 SONSTIGE       3  73.08

# nur die Umfrage für erste Zeile:
elong$survey[[1]]
## # A tibble: 7 × 3
##      PARTY PERCENT  VOTES
##      <chr>   <dbl>  <dbl>
## 1      CDU      35 852.60
## 2      SPD      31 755.16
## 3   GRUENE       7 170.52
## 4      FDP       6 146.16
## 5    LINKE       9 219.24
## 6      AFD       9 219.24
## 7 SONSTIGE       3  73.08


## mit der map_* familie von funktionen aus dem purrr package kann man 
# mit diesen Listen-Spalten wieder ganz normal arbeiten
# hier redundant, weil gesamtsume befragter bereits bekannt, 
# aber genügt zur illustration:
elong %<>% mutate(Befragte2 = map_dbl(survey, function(x) sum(x$VOTES)))
head(elong)
## # A tibble: 6 × 6
##        DATUM      START        END BEFRAGTE           survey Befragte2
##       <date>     <date>     <date>    <dbl>           <list>     <dbl>
## 1 2017-04-15 2017-04-06 2017-04-12     2436 <tibble [7 × 3]>      2436
## 2 2017-04-08 2017-03-30 2017-04-05     1958 <tibble [7 × 3]>      1958
## 3 2017-04-01 2017-03-23 2017-03-29     2416 <tibble [7 × 3]>      2416
## 4 2017-03-25 2017-03-16 2017-03-22     2450 <tibble [7 × 3]>      2450
## 5 2017-03-18 2017-03-09 2017-03-15     1832 <tibble [7 × 3]>      1832
## 6 2017-03-11 2017-03-02 2017-03-08     1882 <tibble [7 × 3]>      1882
```

**Comment by MarHai** [comment]
Sounds good. Je besser an anderes anknüpfbar, desto besser. Und wenn du alle Infos unterbringst, die im Lastenheft angesprochen werden, bin ich damit glücklich. 

Bei einem Update abhängiger Pakete müssen wir ohnehin checken, ob noch alles so läuft, wie es soll, aber dafür schreibst du ja auch die Tests.

Insofern: Go!
