### ISSUE TITLE
allow election_date as a column in pv$data and pv$election_result

### ISSUE THREAD

**Issue by maierhofert** [pollyvote/pollyvoter#6]
thsi column contains the date of the election. This can be useful to differentiate between the date of the predictiona nd the date of the election.

**Comment by maierhofert** [comment]
maybe easier to just replace 
 rename(percent = percent.x, percent.true = percent.y)
with
 rename(percent = percent.x, percent.true = percent.y,
             date = date.x, election_date = date.y)
in initial pv function

**Comment by maxim199008** [comment]
done
