### ISSUE TITLE
documentation missing for pv$predictions$pollyvote

### ISSUE THREAD

**Issue by MarHai** [pollyvote/pollyvoter#9]
`?pv$predictions$pollyvote` is missing

**Comment by MarHai** [comment]
Ah, jetzt checke ich das. Das ist unter `?initial_prediction_pollyvote` ...
Lässt sich das irgendwie einfacher auffinden? Oder in der `print` des PollyVote-Objekts zumindest kurz beschreiben, wo die Hilfeseiten sind?

Bei `?initial_prediction_aggr_source_type` fehlt außerdem noch die Beschreibung.

**Comment by MarHai** [comment]
... und bei `?initial_prediction_pollyvote` fehlt auch die Beschreibung

**Comment by MarHai** [comment]
Und noch was: In der Vignette ist der Funktionsaufruf als `predict(pv, method="pollyvote")` dokumentiert. Das ist zwar richtig, ich finds aber ziemlich irreführend, weil wir damit drei Aufrufvarianten haben (über `pv$predictions$pollyvote`, über `initial_predicition_pollyvote` und eben über `predict`). Vielleicht ist es klüger, in der Vignette zwar kurz zu erwähnen, dass die PV-Funktionen an dieser Stelle `predict` nutzen, den Beispielaufruf aber über die PV-internen Funktionen zu zeigen.

**Comment by maierhofert** [comment]
Das Paket ist so konzipiert, dass die internen Funktionen pv$...$...() nicht verwendet werden müssen oder sollen. Alle Aufrufe sollten indirekt über predict(pv, method = "...") passieren.
Ich habe die Dokumentation von create_pollyvote noch ewtas erweitert und hoffe, dass es damit etwas klarer ist. Die initial_..._... Funktionen sind nur exportiert (also für den Nuetzer sehbar, um eine Dokumentation zur Verfügung zu stellen.
